// react-books/src/components/BookForm.tsx
import { useEffect, useState } from 'react'
import type { Book } from '../types/book'

interface Props {
  show: boolean
  book: Book | null
  onClose: () => void
  onSave: (data: Book) => void
}

export default function BookForm({ show, book, onClose, onSave }: Props) {
  const [form, setForm] = useState<Book>({
    title: '',
    author: '',
    year: new Date().getFullYear(),
    description: ''
  })

  useEffect(() => {
    if (book) {
      setForm(book)
    } else {
      setForm({
        title: '',
        author: '',
        year: new Date().getFullYear(),
        description: ''
      })
    }
  }, [book])

  if (!show) return null

  return (
    <div style={{ position: 'fixed', inset: 0, background: '#00000088' }}>
      <div style={{ background: 'white', padding: 20, margin: '100px auto', width: 300 }}>
        <h3>{book ? 'Edit Book' : 'Create Book'}</h3>

        <input
          value={form.title}
          placeholder="Title"
          onChange={(e) => setForm({ ...form, title: e.target.value })}
        /><br /><br />

        <input
          value={form.author}
          placeholder="Author"
          onChange={(e) => setForm({ ...form, author: e.target.value })}
        /><br /><br />

        <input
          type="number"
          value={form.year}
          placeholder="Year"
          onChange={(e) => setForm({ ...form, year: Number(e.target.value) })}
        /><br /><br />

        <input
          value={form.description}
          placeholder="Description"
          onChange={(e) => setForm({ ...form, description: e.target.value })}
        /><br /><br />

        <button onClick={() => onSave(form)}>Save</button>
        <button onClick={onClose}>Cancel</button>
      </div>
    </div>
  )
}

// vue-books/src/components/BookForm.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import type { Book } from '../models/book'

const props = defineProps<{
  show: boolean
  book: Book | null
}>()

const emit = defineEmits(['close', 'save'])

const form = ref<Book>({
  title: '',
  author: '',
  year: new Date().getFullYear(),
  description: ''
})

watch(() => props.book, (val) => {
  if (val) {
    form.value = { ...val }
  } else {
    resetForm()
  }
})

const resetForm = () => {
  form.value = {
    title: '',
    author: '',
    year: new Date().getFullYear(),
    description: ''
  }
}

const submit = () => {
  emit('save', form.value)
  resetForm()
}
</script>

<template>
  <div v-if="show" style="position:fixed; inset:0; background:#00000088;">
    <div style="background:white;padding:20px;margin:100px auto;width:300px;">
      <h3>{{ book ? 'Edit Book' : 'Create Book' }}</h3>

      <input v-model="form.title" placeholder="Title" /><br /><br />
      <input v-model="form.author" placeholder="Author" /><br /><br />
      <input v-model.number="form.year" type="number" placeholder="Year" /><br /><br />
      <input v-model="form.description" placeholder="Description" /><br /><br />

      <button @click="submit">Save</button>
      <button @click="resetForm(); emit('close')">Cancel</button>
    </div>
  </div>
</template>
